#!/usr/bin/python3
"""
This is a python script that creates a class named City
"""
from model_state import Base, State
from sqlalchemy import Column, Integer, String, ForeignKey
from sqlalchemy.ext.declarative import declarative_base


class City(Base):
    """
    City - inherits from the base, and links to the MySQL table cities
    id - represents a column of an autogenerated, unique integer (Not null)
    name - represents a string with the max chars of 128 (Not null)
    state_id - represents a column on an int, it is a foreign key
    """
    __tablename__ = 'cities'
    id = Column(Integer, autoincrement=True, nullable=False, primary_key=True)
    name = Column(String(128), nullable=False)
    state_id = Column(Integer, ForeignKey("states.id"), nullable=False)
